[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3.9
ansible_ssh_common_args='-o ProxyJump=root@210.140.171.140'

[misc]
sandbox-misc-01

[vds_network]
sandbox-vds-network-01

[docker:children]
vds_network
